/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import javax.swing.JFrame;

/**
 *
 * @author marie
 */
public class JFramePresentacion extends javax.swing.JFrame {
    
    private JFrameGameScreen gamescreen;
    private JFrameInstrucciones instruccion;
    private JFrameCreditos creditos;

    public void setGamescreen(JFrameGameScreen gamescreen) {
        this.gamescreen = gamescreen;
    }

    public void setInstruccion(JFrameInstrucciones instruccion) {
        this.instruccion = instruccion;
    }

    
    

    public void setCreditos(JFrameCreditos creditos) {
        this.creditos = creditos;
    }

    
    /**
     * Creates new form JFramePortada
     */
    public JFramePresentacion() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Pantalla completa
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelLamparaGif = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jLabelTitulo1Sombra = new javax.swing.JLabel();
        jLabelTitulo2Sombra = new javax.swing.JLabel();
        jLabelInstrucciones = new javax.swing.JLabel();
        jLabelRegistros = new javax.swing.JLabel();
        jLabelCreditos = new javax.swing.JLabel();
        jLabelJugar = new javax.swing.JLabel();
        jLabelNube6 = new javax.swing.JLabel();
        jLabelNube1 = new javax.swing.JLabel();
        jLabelNube2 = new javax.swing.JLabel();
        jLabellNube3 = new javax.swing.JLabel();
        jLabelNube4 = new javax.swing.JLabel();
        jLabelNube5 = new javax.swing.JLabel();
        jLabelTituloDisney = new javax.swing.JLabel();
        jLabelPortada1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanelPrincipal.setBackground(new java.awt.Color(163, 208, 241));
        jPanelPrincipal.setLayout(null);

        jLabelTitulo1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setFont(new java.awt.Font("Comic Sans MS", 1, 150)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setText("¿ A D I V I N A");
        jPanelPrincipal.add(jLabelTitulo1);
        jLabelTitulo1.setBounds(310, 150, 1380, 250);

        jLabelLamparaGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/lamparaPixar.gif"))); // NOI18N
        jPanelPrincipal.add(jLabelLamparaGif);
        jLabelLamparaGif.setBounds(690, 280, 482, 331);

        jLabelTitulo2.setFont(new java.awt.Font("Comic Sans MS", 1, 150)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setText("Q U  É N ?");
        jPanelPrincipal.add(jLabelTitulo2);
        jLabelTitulo2.setBounds(560, 350, 1020, 250);

        jLabelTitulo1Sombra.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1Sombra.setFont(new java.awt.Font("Comic Sans MS", 1, 150)); // NOI18N
        jLabelTitulo1Sombra.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTitulo1Sombra.setText("¿ A D I V I N A ");
        jPanelPrincipal.add(jLabelTitulo1Sombra);
        jLabelTitulo1Sombra.setBounds(300, 170, 2506, 210);

        jLabelTitulo2Sombra.setFont(new java.awt.Font("Comic Sans MS", 1, 150)); // NOI18N
        jLabelTitulo2Sombra.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTitulo2Sombra.setText("Q U  É N ?");
        jPanelPrincipal.add(jLabelTitulo2Sombra);
        jLabelTitulo2Sombra.setBounds(550, 330, 990, 280);

        jLabelInstrucciones.setBackground(new java.awt.Color(204, 204, 255));
        jLabelInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/pelotaInstrucciones.png"))); // NOI18N
        jLabelInstrucciones.setText("Pelota");
        jLabelInstrucciones.setPreferredSize(new java.awt.Dimension(290, 290));
        jLabelInstrucciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInstruccionesMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(jLabelInstrucciones);
        jLabelInstrucciones.setBounds(240, 640, 290, 290);

        jLabelRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/Registros.png"))); // NOI18N
        jLabelRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistrosMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(jLabelRegistros);
        jLabelRegistros.setBounds(710, 650, 130, 250);

        jLabelCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/casaCreditos.png"))); // NOI18N
        jLabelCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCreditosMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(jLabelCreditos);
        jLabelCreditos.setBounds(1000, 640, 180, 282);

        jLabelJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/naveJugar.png"))); // NOI18N
        jLabelJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelJugarMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(jLabelJugar);
        jLabelJugar.setBounds(1350, 670, 330, 250);

        jLabelNube6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/nube.png"))); // NOI18N
        jPanelPrincipal.add(jLabelNube6);
        jLabelNube6.setBounds(1580, 40, 150, 110);

        jLabelNube1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/nube.png"))); // NOI18N
        jPanelPrincipal.add(jLabelNube1);
        jLabelNube1.setBounds(130, 40, 150, 110);

        jLabelNube2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/nube.png"))); // NOI18N
        jPanelPrincipal.add(jLabelNube2);
        jLabelNube2.setBounds(330, 40, 150, 110);

        jLabellNube3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/nube.png"))); // NOI18N
        jPanelPrincipal.add(jLabellNube3);
        jLabellNube3.setBounds(520, 40, 150, 110);

        jLabelNube4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/nube.png"))); // NOI18N
        jPanelPrincipal.add(jLabelNube4);
        jLabelNube4.setBounds(1190, 40, 150, 110);

        jLabelNube5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/nube.png"))); // NOI18N
        jPanelPrincipal.add(jLabelNube5);
        jLabelNube5.setBounds(1380, 40, 150, 110);

        jLabelTituloDisney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/disneyTitulo.png"))); // NOI18N
        jPanelPrincipal.add(jLabelTituloDisney);
        jLabelTituloDisney.setBounds(790, 50, 300, 120);

        getContentPane().add(jPanelPrincipal);
        jPanelPrincipal.setBounds(30, 0, 1960, 1030);

        jLabelPortada1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPortada1.setFont(new java.awt.Font("Comic Sans MS", 1, 150)); // NOI18N
        jLabelPortada1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPortada1.setText("¿ A D I V I N A ");
        getContentPane().add(jLabelPortada1);
        jLabelPortada1.setBounds(450, 210, 2506, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJugarMouseClicked
        // TODO add your handling code here:
        JFrameRegistro registro = new JFrameRegistro();
        registro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelJugarMouseClicked

    private void jLabelCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCreditosMouseClicked
        // TODO add your handling code here:
        if (creditos == null) {
            creditos = new JFrameCreditos();
            creditos.setPresentacion(this);
        }
        creditos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCreditosMouseClicked

    private void jLabelRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrosMouseClicked
        // TODO add your handling code here:
        BaseDeDatos base = new BaseDeDatos();
        base.setVisible(true);
    }//GEN-LAST:event_jLabelRegistrosMouseClicked

    private void jLabelInstruccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInstruccionesMouseClicked
        // TODO add your handling code here:
        if (instruccion == null) {
            instruccion = new JFrameInstrucciones();
            instruccion.setPresentacion(this);
        }
        instruccion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelInstruccionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePresentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCreditos;
    private javax.swing.JLabel jLabelInstrucciones;
    private javax.swing.JLabel jLabelJugar;
    private javax.swing.JLabel jLabelLamparaGif;
    private javax.swing.JLabel jLabelNube1;
    private javax.swing.JLabel jLabelNube2;
    private javax.swing.JLabel jLabelNube4;
    private javax.swing.JLabel jLabelNube5;
    private javax.swing.JLabel jLabelNube6;
    private javax.swing.JLabel jLabelPortada1;
    private javax.swing.JLabel jLabelRegistros;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo1Sombra;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelTitulo2Sombra;
    private javax.swing.JLabel jLabelTituloDisney;
    private javax.swing.JLabel jLabellNube3;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
