/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import javax.swing.JFrame;

/**
 *
 * @author marie
 */
public class JFramePresentacion extends javax.swing.JFrame {
    
    private JFrameGameScreen gamescreen;
    private JFrameInstrucciones instruccion;
    private JFrameCreditos creditos;

    public void setGamescreen(JFrameGameScreen gamescreen) {
        this.gamescreen = gamescreen;
    }

    public void setInstruccion(JFrameInstrucciones instruccion) {
        this.instruccion = instruccion;
    }

    
    

    public void setCreditos(JFrameCreditos creditos) {
        this.creditos = creditos;
    }

    
    /**
     * Creates new form JFramePortada
     */
    public JFramePresentacion() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Pantalla completa
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPortada = new javax.swing.JLabel();
        jButtonIrJuego = new javax.swing.JButton();
        jButtonInstruccion = new javax.swing.JButton();
        jButtonCredito = new javax.swing.JButton();
        jButtonInformacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabelPortada.setFont(new java.awt.Font("Centaur", 1, 150)); // NOI18N
        jLabelPortada.setText("¿ A D I V I N A ");
        getContentPane().add(jLabelPortada);
        jLabelPortada.setBounds(450, 210, 2506, 172);

        jButtonIrJuego.setText("Ir a pantalla de juego");
        jButtonIrJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIrJuego);
        jButtonIrJuego.setBounds(830, 700, 140, 23);

        jButtonInstruccion.setText("Instruccion");
        jButtonInstruccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstruccionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInstruccion);
        jButtonInstruccion.setBounds(610, 710, 89, 23);

        jButtonCredito.setText("Credito");
        jButtonCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreditoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCredito);
        jButtonCredito.setBounds(890, 790, 72, 23);

        jButtonInformacion.setText("Informacion");
        jButtonInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInformacion);
        jButtonInformacion.setBounds(1180, 700, 95, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/lamparaPixar.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(730, 310, 482, 331);

        jLabel2.setFont(new java.awt.Font("Centaur", 1, 150)); // NOI18N
        jLabel2.setText("Q U   É N ?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(650, 410, 706, 252);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1960, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 1960, 1030);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIrJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrJuegoActionPerformed
        // TODO add your handling code here:
        if (gamescreen == null) {
            gamescreen = new JFrameGameScreen();
            //gamescreen.setPresentacion(this);
        }
        gamescreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonIrJuegoActionPerformed

    private void jButtonInstruccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstruccionActionPerformed
        // TODO add your handling code here:
        if (instruccion == null) {
            instruccion = new JFrameInstrucciones();
            instruccion.setPresentacion(this);
        }
        instruccion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonInstruccionActionPerformed

    private void jButtonCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreditoActionPerformed
        // TODO add your handling code here:
        if (creditos == null) {
            creditos = new JFrameCreditos();
            creditos.setPresentacion(this);
        }
        creditos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCreditoActionPerformed

    private void jButtonInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformacionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePresentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCredito;
    private javax.swing.JButton jButtonInformacion;
    private javax.swing.JButton jButtonInstruccion;
    private javax.swing.JButton jButtonIrJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPortada;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
