/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import javax.swing.JFrame;

/**
 *
 * @author marie
 */
public class JFramePresentacion extends javax.swing.JFrame {
    
    private JFrameGameScreen gamescreen;
    private JFrameInstrucciones instruccion;
    private JFrameCreditos creditos;

    public void setGamescreen(JFrameGameScreen gamescreen) {
        this.gamescreen = gamescreen;
    }

    public void setInstruccion(JFrameInstrucciones instruccion) {
        this.instruccion = instruccion;
    }

    
    

    public void setCreditos(JFrameCreditos creditos) {
        this.creditos = creditos;
    }

    
    /**
     * Creates new form JFramePortada
     */
    public JFramePresentacion() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Pantalla completa
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPortada = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelInstrucciones = new javax.swing.JLabel();
        jLabelRegistros = new javax.swing.JLabel();
        jLabelCreditos = new javax.swing.JLabel();
        jLabelJugar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelPortada1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(163, 208, 241));
        jPanel1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 150)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("¿ A D I V I N A");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(310, 150, 1380, 250);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/lamparaPixar.gif"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(690, 280, 482, 331);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 150)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Q U  É N ?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(560, 350, 1020, 250);

        jLabelPortada.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPortada.setFont(new java.awt.Font("Comic Sans MS", 1, 150)); // NOI18N
        jLabelPortada.setForeground(new java.awt.Color(153, 153, 153));
        jLabelPortada.setText("¿ A D I V I N A ");
        jPanel1.add(jLabelPortada);
        jLabelPortada.setBounds(300, 170, 2506, 210);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 150)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Q U  É N ?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(550, 330, 990, 280);

        jLabelInstrucciones.setBackground(new java.awt.Color(204, 204, 255));
        jLabelInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/pelotaInstrucciones.png"))); // NOI18N
        jLabelInstrucciones.setText("Pelota");
        jLabelInstrucciones.setPreferredSize(new java.awt.Dimension(290, 290));
        jLabelInstrucciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInstruccionesMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelInstrucciones);
        jLabelInstrucciones.setBounds(240, 640, 290, 290);

        jLabelRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/Registros.png"))); // NOI18N
        jLabelRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistrosMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelRegistros);
        jLabelRegistros.setBounds(710, 650, 130, 250);

        jLabelCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/casaCreditos.png"))); // NOI18N
        jLabelCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCreditosMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelCreditos);
        jLabelCreditos.setBounds(1000, 640, 180, 282);

        jLabelJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/naveJugar.png"))); // NOI18N
        jLabelJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelJugarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelJugar);
        jLabelJugar.setBounds(1350, 670, 330, 250);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/nube.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1580, 40, 150, 110);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/nube.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 40, 150, 110);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/nube.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(330, 40, 150, 110);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/nube.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(520, 40, 150, 110);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/nube.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1190, 40, 150, 110);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/nube.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1380, 40, 150, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disenoPantallas/disneyTitulo.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(790, 50, 300, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 0, 1960, 1030);

        jLabelPortada1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPortada1.setFont(new java.awt.Font("Comic Sans MS", 1, 150)); // NOI18N
        jLabelPortada1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPortada1.setText("¿ A D I V I N A ");
        getContentPane().add(jLabelPortada1);
        jLabelPortada1.setBounds(450, 210, 2506, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJugarMouseClicked
        // TODO add your handling code here:
        JFrameRegistro registro = new JFrameRegistro();
        registro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelJugarMouseClicked

    private void jLabelCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCreditosMouseClicked
        // TODO add your handling code here:
        if (creditos == null) {
            creditos = new JFrameCreditos();
            creditos.setPresentacion(this);
        }
        creditos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCreditosMouseClicked

    private void jLabelRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrosMouseClicked
        // TODO add your handling code here:
        BaseDeDatos base = new BaseDeDatos();
        base.setVisible(true);
    }//GEN-LAST:event_jLabelRegistrosMouseClicked

    private void jLabelInstruccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInstruccionesMouseClicked
        // TODO add your handling code here:
        if (instruccion == null) {
            instruccion = new JFrameInstrucciones();
            instruccion.setPresentacion(this);
        }
        instruccion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelInstruccionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePresentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCreditos;
    private javax.swing.JLabel jLabelInstrucciones;
    private javax.swing.JLabel jLabelJugar;
    private javax.swing.JLabel jLabelPortada;
    private javax.swing.JLabel jLabelPortada1;
    private javax.swing.JLabel jLabelRegistros;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
